language: node_js
node_js:
  - node

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - node_modules

before_script:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: master
    tags: true
