language: node_js
node_js:
  - node

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run build

before_deploy:
  - rm bundle/.gitignore # Make sure that the bundle will be pushed

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
    tags: true
